name: Test pull request

on:
    workflow_dispatch: 
    pull_request:

jobs:
  tests:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: testdatabase
          MYSQL_ROOT_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
            php-version: '8.2'

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - uses: php-actions/composer@v6
      with:
        version: '2.7.6'

    - name: Install node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm i

    - name: Build vite manifest
      run: npm run build

    - name: Start mysql
      run: 'sudo systemctl start mysql.service'

    - name: Create database
      run: mysql -e 'CREATE DATABASE testdatabase;' -uroot -proot

    - name: Update permissions
      run: sudo chmod -R 777 ./

    - name: Start migration
      run: php artisan migrate:fresh --seed --env=testing

    - name: Start tests
      run: php artisan test --env=testing