name: Test pull request

on:
    workflow_dispatch: 
    pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: testdatabase
          MYSQL_ROOT_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
            php-version: '8.2'

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - uses: php-actions/composer@v6
      with:
        version: '2.7.6'

    - name: Start mysql
      run: 'sudo systemctl start mysql.service'